controller_list:
  - name: fake_arm_controller
    joints:
      - ur1_shoulder_pan_joint
      - ur1_shoulder_lift_joint
      - ur1_elbow_joint
      - ur1_wrist_1_joint
      - ur1_wrist_2_joint
      - ur1_wrist_3_joint
  - name: fake_gripper_controller
    joints:
      []