controller_manager_ns: controller_manager
controller_list:
  - name: arm_follow_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
     - ur2_shoulder_pan_joint
     - ur2_shoulder_lift_joint
     - ur2_elbow_joint
     - ur2_wrist_1_joint
     - ur2_wrist_2_joint
     - ur2_wrist_3_joint
