controller_list:
  - name: fake_arm_controller
    joints:
      - ur2_shoulder_pan_joint
      - ur2_shoulder_lift_joint
      - ur2_elbow_joint
      - ur2_wrist_1_joint
      - ur2_wrist_2_joint
      - ur2_wrist_3_joint
  - name: fake_gripper_controller
    joints:
      []